// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort() {
  return window['go']['main']['App']['Abort']();
}

export function BeginOpenAICodexLogin() {
  return window['go']['main']['App']['BeginOpenAICodexLogin']();
}

export function CancelOpenAICodexLogin() {
  return window['go']['main']['App']['CancelOpenAICodexLogin']();
}

export function Compact() {
  return window['go']['main']['App']['Compact']();
}

export function CompletePath(arg1) {
  return window['go']['main']['App']['CompletePath'](arg1);
}

export function FinishOpenAICodexLogin() {
  return window['go']['main']['App']['FinishOpenAICodexLogin']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Goal(arg1) {
  return window['go']['main']['App']['Goal'](arg1);
}

export function ListAPIKeys() {
  return window['go']['main']['App']['ListAPIKeys']();
}

export function ListCustomProviders() {
  return window['go']['main']['App']['ListCustomProviders']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenRecentFolder(arg1) {
  return window['go']['main']['App']['OpenRecentFolder'](arg1);
}

export function OpenSession(arg1) {
  return window['go']['main']['App']['OpenSession'](arg1);
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function Prompt(arg1, arg2) {
  return window['go']['main']['App']['Prompt'](arg1, arg2);
}

export function RecentDirs() {
  return window['go']['main']['App']['RecentDirs']();
}

export function ReloadMCP() {
  return window['go']['main']['App']['ReloadMCP']();
}

export function RemoveCustomProvider(arg1) {
  return window['go']['main']['App']['RemoveCustomProvider'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResendUserMessage(arg1) {
  return window['go']['main']['App']['ResendUserMessage'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SetMCPServerEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetMCPServerEnabled'](arg1, arg2);
}

export function SetModel(arg1, arg2) {
  return window['go']['main']['App']['SetModel'](arg1, arg2);
}

export function SetSubagentEnabled(arg1) {
  return window['go']['main']['App']['SetSubagentEnabled'](arg1);
}

export function SetThinking(arg1) {
  return window['go']['main']['App']['SetThinking'](arg1);
}

export function UpsertCustomProvider(arg1) {
  return window['go']['main']['App']['UpsertCustomProvider'](arg1);
}

export function UpsertMCPServer(arg1) {
  return window['go']['main']['App']['UpsertMCPServer'](arg1);
}
