// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function Abort():Promise<void>;

export function BeginOpenAICodexLogin():Promise<main.CodexLoginInfo>;

export function CancelOpenAICodexLogin():Promise<void>;

export function Compact():Promise<void>;

export function CompletePath(arg1:string):Promise<Array<main.PathSuggestion>>;

export function FinishOpenAICodexLogin():Promise<void>;

export function GetState():Promise<main.AppState>;

export function ListAPIKeys():Promise<Array<main.APIKeyStatus>>;

export function ListModels():Promise<Array<main.ModelInfo>>;

export function ListSessions():Promise<Array<core.SessionSummary>>;

export function NewSession():Promise<void>;

export function OpenFolder():Promise<string>;

export function OpenRecentFolder(arg1:string):Promise<void>;

export function OpenSession(arg1:string):Promise<void>;

export function PickFiles():Promise<Array<main.PickedFile>>;

export function Prompt(arg1:string,arg2:Array<main.ImageAttachment>):Promise<void>;

export function RecentDirs():Promise<Array<string>>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SetAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetModel(arg1:string,arg2:string):Promise<void>;

export function SetSubagentEnabled(arg1:boolean):Promise<void>;

export function SetThinking(arg1:string):Promise<void>;
