// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort() {
  return window['go']['main']['App']['Abort']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ListAPIKeys() {
  return window['go']['main']['App']['ListAPIKeys']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenSession(arg1) {
  return window['go']['main']['App']['OpenSession'](arg1);
}

export function Prompt(arg1) {
  return window['go']['main']['App']['Prompt'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SetModel(arg1, arg2) {
  return window['go']['main']['App']['SetModel'](arg1, arg2);
}

export function SetThinking(arg1) {
  return window['go']['main']['App']['SetThinking'](arg1);
}
