// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {mcp} from '../models';
import {core} from '../models';

export function Abort():Promise<void>;

export function BeginOpenAICodexLogin():Promise<main.CodexLoginInfo>;

export function CancelOpenAICodexLogin():Promise<void>;

export function Compact():Promise<void>;

export function CompletePath(arg1:string):Promise<Array<main.PathSuggestion>>;

export function FinishOpenAICodexLogin():Promise<void>;

export function GetMCPStatus():Promise<mcp.Status>;

export function GetState():Promise<main.AppState>;

export function Goal(arg1:string):Promise<void>;

export function ListAPIKeys():Promise<Array<main.APIKeyStatus>>;

export function ListCustomProviders():Promise<Array<core.CustomProvider>>;

export function ListMCPServers():Promise<Array<mcp.ServerStatus>>;

export function ListModels():Promise<Array<main.ModelInfo>>;

export function ListSessions():Promise<Array<core.SessionSummary>>;

export function NewSession():Promise<void>;

export function OpenFolder():Promise<string>;

export function OpenRecentFolder(arg1:string):Promise<void>;

export function OpenSession(arg1:string):Promise<void>;

export function PickFiles():Promise<Array<main.PickedFile>>;

export function Prompt(arg1:string,arg2:Array<main.ImageAttachment>):Promise<void>;

export function RecentDirs():Promise<Array<string>>;

export function ReloadMCP():Promise<void>;

export function RemoveCustomProvider(arg1:string):Promise<void>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResendUserMessage(arg1:number):Promise<void>;

export function SetAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetMCPServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetModel(arg1:string,arg2:string):Promise<void>;

export function SetSubagentEnabled(arg1:boolean):Promise<void>;

export function SetThinking(arg1:string):Promise<void>;

export function UpsertCustomProvider(arg1:core.CustomProvider):Promise<void>;

export function UpsertMCPServer(arg1:main.MCPServerInput):Promise<void>;
